@startuml
actor Teacher as Actor
boundary UI

activate Actor

Actor -> UI: Schedule an extraordinary class
activate UI
UI --> Actor: Authorization status
deactivate UI
alt if authorized
    UI --> Actor: Course list
    activate UI
    Actor -> UI: Course selection
    deactivate UI
    UI --> Actor: Asks for Class Title
    activate UI
    Actor -> UI: Class Title
    deactivate UI

    UI -> Actor: Asks for Class Date
    activate UI
    Actor -> UI: Class Date
    deactivate UI
    UI -> Actor: Asks for Class Start Time
    activate UI
    Actor -> UI: Class Start Time
    deactivate UI
    UI -> Actor: Asks for Class End Time
    activate UI
    Actor -> UI: Class End Time
    deactivate UI
    loop while list of students not empty
    UI -> Actor: Asks for Student Selection
    activate UI
    Actor -> UI: Student Selection
    deactivate UI
    end
    alt if user is available

        UI -> Actor: Class creation status
        activate UI
    else
        UI -> Actor: Inform user is not available
    end
else
    UI -> Actor: Inform user is not authorized
    deactivate UI
end

@enduml
