@startuml

class ScheduleExtraordinaryClassUI {
  + ScheduleExtraordinaryClassUI():
  # doShow(): boolean
  + headline(): String
  - readTime(String): LocalTime
  - chooseCourse(Iterable<Course>): Course
  - chooseStudent((List<Student>): Student
   userWeekdayInput: String
}

class CheckIfUserIsFreeService <<Service>> {
    + checkIfUserIsFree(user, date) : boolean


}

class CourseClass{
 -   classTitle: String
 -   course: Course
 -   dateOfCourseClass: Date
 -   endTime: LocalTime
 -   id: Long
 -   startTime: LocalTime
 -   students: List&lt;Student&gt;
 -   teacher: Teacher
 -   version: Long
 -   weekDay: String
+ classTitle(): String
- getDurationInMinutes(startTime: LocalTime, endTime
+ identity(): Long
- isDateAfterCurrentDate(date: Date): boolean
+ isValidWeekday(weekday: String): boolean
+ sameAs(other: Object): boolean
- validateClassTime(startTime: LocalTime, endTime:
- validateTitle(title: String): boolean

}


class ScheduleExtraordinaryClassController {
  + ScheduleExtraordinaryClassController():
  + listCourses(): Iterable<Course>
  + checkAndGetDate(String): Date
  + createCourseClass(Teacher, String, Date, String, LocalTime, LocalTime, Course, List<Student>): void
  + getScheduleOfTeacher(): void
  + listStudentsByCourse(Course): List<Student>
  + isTimeRangeValid(LocalTime, LocalTime): boolean
  + checkCourseClass(List<SystemUser>, String, Date, LocalTime, LocalTime): boolean
  - appendScheduleEntries(StringBuilder, List<?>): void
  + getWeekdayFromDate(Date): String
  + isTitleValid(String): boolean
  - formatScheduleEntry(Object): String
   teacher: Teacher
}





class CourseClassBuilder {
  + CourseClassBuilder():
  + withDateOfCourseClass(Date): CourseClassBuilder
  + withCourse(Course): CourseClassBuilder
  + withTeacher(Teacher): CourseClassBuilder
  + build(): CourseClass
  + withStudents(List<Student>): CourseClassBuilder
  + withWeekDays(String): CourseClassBuilder
  + withClassTitle(String): CourseClassBuilder
  + withStartTime(LocalTime): CourseClassBuilder
  + withEndTime(LocalTime): CourseClassBuilder
}



class CheckIfUserIsFreeService {
  + CheckIfUserIsFreeService():
  - checkIfDatesCoincide(Date, LocalTime, LocalTime, List<CourseClass>, List<Meeting>, List<MeetingInvitation>): boolean
  - isTimeOverlap(LocalTime, LocalTime, LocalTime, LocalTime): boolean
  + checkIfUserIsNotFree(SystemUser, Date, LocalTime, LocalTime): boolean
}




interface CourseClassRepository << interface >> {
  + findClassesOfStudent(Student): Iterable<CourseClass>
  + findClassOfTitleAndDate(String, Date): Iterable<CourseClass>
  + findClassesOfTeacherOnDate(Teacher, Date): Iterable<CourseClass>
  + findClassesOfStudentOnDate(Student, Date): Iterable<CourseClass>
  + findAllCourseClasses(): Iterable<CourseClass>
  + findCourseClassByTitle(String): CourseClass
  + findClassesOfTeacher(Teacher): Iterable<CourseClass>
}






ScheduleExtraordinaryClassUI ..> ScheduleExtraordinaryClassController
ScheduleExtraordinaryClassController ..> CourseClassBuilder
ScheduleExtraordinaryClassController ..> CourseClass
ScheduleExtraordinaryClassController ..> CourseClassRepository
ScheduleExtraordinaryClassController ..> CheckIfUserIsFreeService
CheckIfUserIsFreeService ..> CourseClassRepository
CourseClassRepository ..> CourseClass
CourseClassBuilder ..> CourseClass



@enduml