@startuml
'https://plantuml.com/sequence-diagram
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

autonumber

actor Manager as Actor
participant listAvailableCoursesUI as UI <<presentation>>


Actor -> UI: Wants to see the courses available to him
activate UI
    create control listAvailableCoursesController
    UI -> listAvailableCoursesController: create()
    UI -> listAvailableCoursesController: listCoursesAvailableForManager()
    activate listAvailableCoursesController
        database CourseRepository as Repository <<repository>>
        listAvailableCoursesController -> Repository: findAll()
        activate Repository
            Repository --> listAvailableCoursesController
        deactivate Repository
        listAvailableCoursesController --> UI
    deactivate listAvailableCoursesController

    UI -> UI: display the list
    UI --> Actor
deactivate UI
@enduml