@startuml

skinparam groupInheritance 0
!theme amiga
skinparam linetype ortho

package User {

abstract class User <<Aggregate Root>>{
}

class UserID <<Value Object>>{
int: userID
}

class FullName <<Value Object>>{
String: fullName
}

class ShortName <<Value Object>>{
String: shortName
}

class BirthDate <<Value Object>> {
        Date: birthDate
}

class TaxNumber <<Value Object>> {
        Integer: taxNumber
}

class Email <<Value Object>> {
    String: email
}

class Password <<Value Object>> {
    String: password
}

User --* UserID
User --* FullName
User --* ShortName
User --* BirthDate
User --* Email
User --* Password
User --* TaxNumber

}

package Student {

class Student <<Aggregate Root>> {
}

class MechanographicNumber <<Value Object>> {
        Integer: mechanographicNumber
}

Student --* MechanographicNumber

}

package Teacher {

class Teacher <<Aggregate Root>> {
}

class Acronym <<Value Object>>{
    String: acronym
}

Teacher --* Acronym

}

package Manager {

class Manager <<Aggregate Root>> {
}

}

package Course {

class Course <<Aggregate Root>> {
            Long: courseID
            String: courseCode
            String: description
            Integer: minStudents
            Integer: maxStudents
            Teacher: teacherInCharge
            Date: openCourseDate
            Date: closeCourseDate
            Date: openEnrollmentsDate
            Date: closeEnrollmentsDate

}


class CourseName <<Value Object>> {
    String: courseName
}

enum CourseStatus {
        CLOSE
        OPEN
        ENROLL
        IN_PROGRESS
}

Course ---* CourseName
Course "1" ---> "1" CourseStatus: has >


}

package Class {

class CourseClass <<Aggregate Root>> {
    Long: id
    String: classTitle
    Date: dateOfCourseClass
    String: weekDay
    LocalTime: startTime
    LocalTime: endTime
}
}

package Enrollment {

class Enrollment <<Aggregate Root>> {
    Long: enrollmentId
    Student: student
    Course: course

}

class ExamEnrollment <<Entity>> {
    Long: examID
    Enrollment: enrollment
    Grade: examGrade
}

class EnrollmentStatus{
   NOT ACCEPTED
   UNDER APPRECIATION
   ACCEPTED
}

enum ExamEnrollmentStatus {
    ENROLLED
    PRESENT
    MISSED
}

class Grade {
    float: grade
}

ExamEnrollment ---* Grade
Enrollment "1" ---> "1" EnrollmentStatus: has >
ExamEnrollment "1" --> "1" ExamEnrollmentStatus: has >
Enrollment "1" --> "*" ExamEnrollment : has

}

package Teaching {

class Teaching <<Aggregate Root>>{
    Long: id
    Teacher: teacher
    Course: course
    boolean: isPrimary
}

}

package Exam {

class Exam <<Aggregate Root>> {
Long: examID
String: title
String: description
Date: openDate
Date: closeDate
}

enum ExamStatus {
CREATED
FINISHED
}


class Header {
    String: headerDescription
}

enum FeedbackType{
NONE
ON-SUBMISSION
AFTER-CLOSING
}

enum GradeType{
NONE
ON-SUBMISSION
AFTER-CLOSING
}

enum ExamFlag <<Value Object>> {
    AUTO
    MANUAL
}

class Language <<Value Object>> {
    String: language
}

class Section {
    String: description
}



ExamFlag *-- Exam
Language *-- Exam
Exam "1" --> "1" Header: has >
Exam "1" --> "*" Section: has >
Exam "1" --> "1" ExamStatus : has >
Header "1" --> "1" GradeType: has >
Header "1" --> "1" FeedbackType: has >

}

package question {

class Question <<Aggregate Root>> {
    Long: questionID
    Section: section
    Course: course
    String: question
    String: correctAnswer
    int: quotation

}

enum QuestionType{
    MATCHING
    MISSING WORD
    MULTIPLE CHOICE
    SHORT
    NUMERIC
    TRUE OR FALSE
}
Question "1" --> "1" QuestionType
Section "1" --> "*" Question
}

package SharedBoard {

class SharedBoard <<Aggregate Root>>{
    Long: sharedBoardId
    String: title
    SystemUser: owner
    int: maxNumberOfRows
    int: maxNumberOfColumns
}

class SharedBoardInvitation{
    Long: inviteeId
    SystemUser: userInvite
    UserPermission: userPermission
}

enum SharedBoardStatus {
    OPEN
    ARCHIVED
}

class Row <<Entity>> {
    Long: rowID
    int: rowNumber
    String: title
}

class SharedBoardColumn <<Entity>> {
    Long: columnID
    int: ColumnNumber
    String: title
}

class Cell <<Entity>> {
    Long: cellID
    Row: rowNumber
    Column: columnNumber
    Boolean: isFree
}

enum UserPermission {
    READ ONLY
    WRITE
}

class PostIt <<Entity>>{
    Long: postItID
    String: content
    SystemUser: owner
    Cell: cell
}

class PostItHistory <<Entity>>{
    PostIt: postIt
    DateTime: timestamp
    String: oldDescription
    String: newDescription
    Cell: oldCell
    Cell: newCell
}

SharedBoard "1" --> "*" SharedBoardInvitation : has >
SharedBoardInvitation "1" --> "1" UserPermission : has >
SharedBoard "1" --> "1" SharedBoardStatus : has >
SharedBoard "1" --> "*" Row : has >
SharedBoard "1" --> "*" SharedBoardColumn : has >
Row "1" --> "*" Cell : has >
SharedBoardColumn "1" --> "*" Cell : has >
PostIt "1" --> "*" PostItHistory : has >
Cell "1" -> "1" PostIt : contains >

}

package Meeting {

class Meeting <<Aggregate Root>>{
    Long: id
    String: description
    LocalTime: startTime
    LocalTime: endTime
    Date: date
    SystemUser: organizer
}

enum MeetingStatus{
    CREATED
    CANCELED
}


class MeetingInvitation <<Entity>>{
    Long: inviteeID
    Meeting: meeting
    Course: course
    SystemUser: invitee
}

enum MeetingInvitationStatus {
    PENDING
    ACCEPTED
    DECLINED
    CANCELED
}


Meeting "1" --> "*" MeetingInvitation : has >
MeetingInvitation "1" -> "1" MeetingInvitationStatus : has >
Meeting "1" -> "1" MeetingStatus : has >
}

package Service{

class CheckIfUserIsFreeService{

}

class CommonTakeExamService {

}

class CreateUpdateExamService {
}

class BulEnrollStudentsService {
}

class ListFutureExamsService {
}

class CreateUpdateQuestionService {

}
}

CheckIfUserIsFreeService --> SystemUser
CheckIfUserIsFreeService --> Teacher
CheckIfUserIsFreeService --> Student

BulEnrollStudentsService --> Enrollment
BulEnrollStudentsService --> Course
BulEnrollStudentsService --> Student

CreateUpdateExamService --> Exam
CommonTakeExamService --> Exam
ListFutureExamsService --> Exam
ListFutureExamsService --> Student
CreateUpdateQuestionService --> Question

User <|-- Teacher
User <|-- Student

Enrollment "*" --[thickness=4]-> "1" Student: are asked >
Enrollment "*" -[thickness=4]--> "1" Course: is of >

Course "1" -[thickness=4]--> "1..*" Exam : is composed of >
User "1" -[thickness=4]--> "*" Enrollment : administrates >
User "1" -[thickness=4]--> "*" Course: manages >
Teacher "1" -[thickness=4]--> "*" CourszeClass : schedules >
Teacher "1" -[thickness=4]--> "*" Exam: creates >
User "1" -[thickness=4]-> "*" SharedBoard: creates >
Teaching "1" -[thickness=4]--> "*" Teacher : is done by >
Teaching "1" -[thickness=4]--> "*" Course : teaches in >
Course "1" -[thickness=4]--> "*" CourseClass: has >
CourseClass "1" -[thickness=4]--> "*" Student: has >
User "1" -[thickness=4]-> "1" Meeting : schedules >

@enduml